typography_spectrum: 0.08233929076232016
color:
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
  brandStrength: 0.6958401289302856
  lightness: 0.8609723025001585
  saturation: 0.3347387264948338
  rhythmicContrast: 0.4558330597355962
github: true
layout_spectrum: 0.618202734272927
author:
  name: 公司法定过分的事
  email: 61938246@qq.com
name: 哥斯达给发送到韩服的花色繁多
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: 富商大贾烦到死给发送到
    url: 'https://cxqq.net'
    type: external
title: 粉红丝带粉红丝带会发生的
content: []
description: ''
